name: Build macOS App

on:
  push:
    paths:
      - '**.py'
      - 'links.json'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install py2app ttkbootstrap

      - name: Create setup.py
        run: |
          echo "
from setuptools import setup

APP = ['main.py']
DATA_FILES = ['links.json']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'icon.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
          " > setup.py

      - name: Build App
        run: python3 setup.py py2app

      - name: Upload App
        uses: actions/upload-artifact@v3
        with:
          name: QuickLaunch-macOS
          path: dist/QuickLaunch.app
